refactored and es6-ified component-conversion
html-next/flexi-dsl pull request #7
Opened 2017-02-15 08:37 UTC by kybishop

Also a few minor improvements to attribute-conversion.js

2017-02-15 19:44 UTC, RobbieTheWagner requested changes
Couple minor issues, but mostly looks good!

2017-02-15 19:44 UTC, rwwagner90 commented on dsl/attribute-conversion.js
> -/* jshint node:true */
Might be able to just say `eslint node:true` here?

2017-02-15 19:44 UTC, rwwagner90 commented on dsl/attribute-conversion.js
> +      if (isComplex && attribute.values.indexOf(value) === -1) {
Can we use `includes` instead of `indexOf` here?

2017-02-15 19:44 UTC, rwwagner90 commented on dsl/attribute-conversion.js
> -    let values = isComplex ? attribute.values : [];
Why do we no longer want to make this an empty array if it's not complex?

2017-02-15 19:48 UTC, kybishop commented on dsl/attribute-conversion.js
> -    let values = isComplex ? attribute.values : [];
the var was created unnecessarily. It is only used on line 193, and an `isComplex` check already occurs right before its usage, so the only state we'd ever arrive in is `attribute.values`.

2017-02-15 19:50 UTC, kybishop commented on dsl/attribute-conversion.js
> +      if (isComplex && attribute.values.indexOf(value) === -1) {
good idea. fixed

2017-02-15 20:09 UTC, kybishop commented on dsl/attribute-conversion.js
> -/* jshint node:true */
Finally found the eslint equiv: `/* eslint-env node */`
fixed

2017-02-15 20:33 UTC, merged

2017-02-16 06:38 UTC, runspired commented
I'm not sure what ember-cli's node support matrix (currently `^4.5`) allows us in terms of ES6 features, I would check with that before going to far down this refactor rabbit hole.

https://github.com/ember-cli/ember-cli/blob/master/package.json#L146

2017-02-16 06:47 UTC, kybishop commented
@runspired luckily travis is true to it's word regarding the node version specified in `.travis`, so it sanity checks the features available. I actually had to revert an `Array.prototype.includes` back to `Array.prototype.indexOf` thanks to a good catch by Travis.

I want to continue supporting the same minimum node version as ember-cli, so I'll be sure to be careful.

My goals with these are:
1. audit the code and remove anything unnecessary
2. use es6 to make thing a little more readable.
3. add comments (see above
4. become more familiar with the code

Apologies if these refactors seem bike shed-ish, or if I'm stepping on toes by making all these changes to something you built from scratch

2017-02-16 07:00 UTC, runspired commented
no toes stepped on, just wanted to ensure we weren't jumping the gun on all the new hotness :)

2017-02-16 07:17 UTC, kybishop commented
🔥